export const browserCoreExamples = [
  "nsemclaw browser status",
  "nsemclaw browser start",
  "nsemclaw browser stop",
  "nsemclaw browser tabs",
  "nsemclaw browser open https://example.com",
  "nsemclaw browser focus abcd1234",
  "nsemclaw browser close abcd1234",
  "nsemclaw browser screenshot",
  "nsemclaw browser screenshot --full-page",
  "nsemclaw browser screenshot --ref 12",
  "nsemclaw browser snapshot",
  "nsemclaw browser snapshot --format aria --limit 200",
  "nsemclaw browser snapshot --efficient",
  "nsemclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "nsemclaw browser navigate https://example.com",
  "nsemclaw browser resize 1280 720",
  "nsemclaw browser click 12 --double",
  'nsemclaw browser type 23 "hello" --submit',
  "nsemclaw browser press Enter",
  "nsemclaw browser hover 44",
  "nsemclaw browser drag 10 11",
  "nsemclaw browser select 9 OptionA OptionB",
  "nsemclaw browser upload /tmp/nsemclaw/uploads/file.pdf",
  'nsemclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nsemclaw browser dialog --accept",
  'nsemclaw browser wait --text "完成"',
  "nsemclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nsemclaw browser console --level error",
  "nsemclaw browser pdf",
];
